# https://taskfile.dev

version: '3'

tasks:
  install:
    desc: "Install all dependencies"
    cmds:
      - npm install --workspaces

  install:backend:
    desc: "Install backend dependencies"
    cmds:
      - npm install -w backend

  install:frontend:
    desc: "Install frontend dependencies"
    cmds:
      - npm install -w frontend

  reinstall:
    desc: "Re-install all dependencies"
    cmds:
      - rm -rf node_modules
      - rm -rf common/node_modules
      - rm -rf backend/node_modules
      - rm -rf frontend/node_modules
      - task: install

  build:
    desc: "Build all applications"
    cmds:
      - npm run build --workspaces

  build:backend:
    desc: "Build the backend application"
    cmds:
      - npm run build -w backend

  build:frontend:
    desc: "Build the frontend application"
    cmds:
      - npm run build -w frontend

  dev:
    desc: "Run all applications"
    deps:
      - task: dev:backend
      - task: dev:frontend

  dev:backend:
    desc: "Run the backend application"
    cmds:
      - npm run dev -w backend

  dev:frontend:
    desc: "Run the frontend application"
    cmds:
      - npm run dev -w frontend

  format:
    desc: "Format files"
    cmds:
      - npm run format --workspaces
